### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by tooolbox** [c9s/c6#86]
Hey @c9s I wanted to check with you on your plans for this project.  There are a couple of native Go ports of the SASS compiler lying around, all abandoned/inactive, but this one seems the furthest along.  I am wondering if you have an idea of how much work is left to make it operational as a SASS-compatible compiler, or at least with the most commonly used features.

I'm asking because I am currently using the Go bindings for libsass, which gives my project a long (for Go) compile time and greatly increases the weight of my binary in MB.  Having a native SASS compiler would be great for myself and many others, I believe.

I am not a parser/compiler buff, but I would be interested in contributing towards making this happen.  (Maybe if there's an example of implementing SASS functions, I could implement some using that pattern?)  Please let me know your thoughts on this project and its future.  Thanks!

**Comment by c9s** [comment]
Hi,

first I want to thank you for the comment. I Originally developed this project because I was working on a few frontend projects which need to compile ~20 thousand lines of SCSS code.
it's really time-consuming and libsass was not stable and fully functional at that time.

I am still looking forward to seeing the project success, however I don't have time working on it for now, and I am getting older, don't have enough physical strength to push these implementation. 

Pull requests are all welcomed. :)

**Comment by tooolbox** [comment]
Thanks very much for the reply @c9s!

> I am still looking forward to seeing the project success, however I don't have time working on it for now, and I am getting older, don't have enough physical strength to push these implementation.

I understand, that's ok :)

> Pull requests are all welcomed. :)

That's why I'm asking.  If you welcome pull requests, then I would like to please ask for more data regarding the project and what are the next steps.  The readme has [a list](https://github.com/c9s/c6#working-in-progress) and from that I can see:

1. Lexing is basically done.
2. Parsing is basically done.
3. No runtime.
4. No built-in functions.
5. No compiler.

That is good information, but here is my main question:

*From your knowledge, what is the sequence of tasks that are needed to get this code compiling some small subset of SASS into finished CSS?*

For example:

*"The next step was to start on the compiler.  I needed to take the parsed AST and output CSS.  My plan was to use algorithm [X] for this, and the tricky part was I needed to build runtime component [Z] so I could import the [Q] files. After that, the work is simple because all that's remaining is [A] and [B]."*

This is important because you had a vision and a plan for how the code would evolve, and if myself or others don't understand that vision, we won't know what to do or will make mistakes.  I am sure that an experienced compiler engineer or a libsass contributor could look at c6 and know what pieces were missing, but I am not those people :)

I hope that makes sense, and I hope you have time to put together an explanation.  The more thorough you make it, the more chance you have of someone stepping up and completing c6 for you.  In any case, I wish you good fortune in your work!
